CREATE DATABASE `betofficetest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'betofficetest'@'localhost' IDENTIFIED BY 'xxx';
CREATE USER 'betofficetest'@'%' IDENTIFIED BY 'xxx';

CREATE USER 'betofficetestsu'@'localhost' IDENTIFIED BY 'xxx';
CREATE USER 'betofficetestsu'@'%' IDENTIFIED BY 'xxx';

REVOKE ALL PRIVILEGES ON * . * FROM 'betofficetest'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'betofficetest'@'%';

REVOKE ALL PRIVILEGES ON * . * FROM 'betofficetestsu'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'betofficetestsu'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON betofficetest. * TO 'betofficetest'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON betofficetest. * TO 'betofficetest'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON betofficetest. * TO 'betofficetestsu'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON betofficetest. * TO 'betofficetestsu'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
  