CREATE DATABASE `betoffice` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER 'betoffice'@'localhost' IDENTIFIED BY 'betoffice';
CREATE USER 'betoffice'@'%' IDENTIFIED BY 'betoffice';

CREATE USER 'betofficesu'@'localhost' IDENTIFIED BY 'betoffice';
CREATE USER 'betofficesu'@'%' IDENTIFIED BY 'betoffice';

REVOKE ALL PRIVILEGES ON * . * FROM 'betoffice'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'betoffice'@'%';

REVOKE ALL PRIVILEGES ON * . * FROM 'betofficesu'@'localhost';
REVOKE ALL PRIVILEGES ON * . * FROM 'betofficesu'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON betoffice. * TO 'betoffice'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE ON betoffice. * TO 'betoffice'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON betoffice. * TO 'betofficesu'@'localhost'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE,
  ALTER, INDEX, DROP, CREATE TEMPORARY TABLES, SHOW VIEW,
  CREATE ROUTINE, ALTER ROUTINE, EXECUTE, CREATE VIEW, EVENT, TRIGGER,
  LOCK TABLES
  ON betoffice. * TO 'betofficesu'@'%'
  WITH GRANT OPTION
  MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0
  MAX_UPDATES_PER_HOUR 0
  MAX_USER_CONNECTIONS 0;
  